/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/pillBottle3.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle001: THREE.Mesh
    Circle_1: THREE.Mesh
    Circle_2: THREE.Mesh
  }
  materials: {
    material2: THREE.MeshStandardMaterial
    img_mat: THREE.MeshStandardMaterial
    material1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/pillBottle3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001.geometry} material={materials.material2} />
      <mesh geometry={nodes.Circle_1.geometry} material={materials.img_mat} />
      <mesh geometry={nodes.Circle_2.geometry} material={materials.material1} />
    </group>
  )
}

useGLTF.preload('/pillBottle3.glb')
