/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/pillBottle.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pillBottle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle_1.geometry} material={materials.img_mat} />
      <mesh geometry={nodes.Circle_2.geometry} >
        <meshNormalMaterial />
      </mesh>
      <mesh geometry={nodes.Circle001.geometry} scale={36.24} />
    </group>
  )
}

useGLTF.preload('/pillBottle.glb')
