/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 components\untitled.glb 
*/

import React, { useRef } from 'react'
import { Plane, useGLTF, Environment } from '@react-three/drei'

export default function Model(props) {
  
  const { nodes, materials } = useGLTF('/compressed.glb')
  return (
    <>
    <group {...props} dispose={null} scale={0.05} position={[-3, -2, -2.5]} >
      <mesh geometry={nodes['Hladík^Jakub'].geometry}  >
        <meshPhysicalMaterial transmission={1} thickness={1} color={"lightblue"} transparent roughness={0}/>
      </mesh>
    </group>
    </>
  )
}

useGLTF.preload('/compressed.glb')
